# Dependencies
markdown:	kramdown
# Permalinks
permalink:	:year/:title

# Setup
baseurl:

title:		Humrich
tagline:	'Nicks blog'
description:	'Blog for Nick Humrich'
url:		http://blog.humrich.us
commentsystem:	disqus
disqus:		humrichblog

author:
  name:		'Nick Humrich'
  url:		https://blog.humrich.us

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  # - icon: {icon name from FontAwesome (without the fa-)}
  - icon:	twitter
    url:	https://twitter.com/nhumrich
    desc:	Follow me on twitter

  - icon:   stack-overflow
    url:    http://stackoverflow.com/users/2434234/nick-humrich
    desc:   View my StackOverflow profile
    
  - icon:	github
    url:	https://github.com/nhumrich
    desc:	Fork me on github

  - icon:   envelope
    url:    mailto:nick@humrich.us
    desc:   Send me an email
  
  - icon:	linkedin
    url:	https://www.linkedin.com/in/nhumrich/
    desc:	View my profile on LinkedIn
    
  - icon:	rss
    url:	/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about
    

copyright:
  author:	Nick Humrich
  url:		http://blog.humrich.us
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by/4.0/

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-56753640-1
